realtor_client/apartment/urls.py
from django.urls import path
from . import models

app_name = 'apartment'

urlpatterns = [
    path('', models.authenticate, name="apartment"),
    path('offer', models.set_offer, name="offer"),
]

realtor_client/home/urls.py
from django.urls import path

from .views import HomeView, LoginView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login', LoginView.as_view(), name="login"),
]

realtor_client/realtor_client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls',namespace='home')),
    path('apartment', include('apartment.urls',namespace='apartment')),
]

realtor_client/apartment/models.py
from django.db import models
from django.http import HttpResponseRedirect
import xmlrpc.client
from django.shortcuts import render

def get_apartment(): 
    allApartment = models.execute_kw(db, uid, passw, 'apartment.sell', 'search_read', [])
    x = range(0, len(allApartment))
    if len(allApartment) > 0:
        for i in x:
                allApartment[i]['best_offerer'] = allApartment[i]['best_offerer'][1]
                product = models.execute_kw(db, uid, passw, 'product.template', 'search_read',
                 [[('idApart', '=', allApartment[i]['name'])]])
                if len(product) > 0:
                    allApartment[i]['qty_available'] = product[0]['qty_available']
                else:
                    allApartment[i]['qty_available'] = 0
        return allApartment

def set_offer(request):
    value = models.execute_kw(db, uid, passw, 'res.partner', 'search_read', [[('name', '=', request.POST["offerer"])]])
    if not value :
        create(request.POST["offerer"])

    if float(request.POST["amount"]) > float(request.POST["best_offer"]):
        offer = get_offer_by_name(request.POST["offerer"])
        models.execute_kw(db, uid, passw, 'apartment.sell','write',[[int(request.POST["apartment"])],
    {'best_offerer' : offer[0]['id'],
    'best_price_offer': int(request.POST["amount"])}])
    else :
        return render(request,'apartment/apartment.html', {'apartments': get_apartment(),'connected' : "True", 
        'error' : "You need to enter an amount above the current best offer " + request.POST["best_offer"], 'apart_offer' : request.POST["apartment"]})
    return render(request,'apartment/apartment.html', {'apartments': get_apartment(),'connected' : "True"})
    
def authenticate(request):
    if(request.POST['connected'] == "False"):
        global user
        global passw
        global uid
        global url
        global db
        global common
        global models
        url = request.POST['url']
        common = xmlrpc.client.ServerProxy(
            '{}/xmlrpc/2/common'.format(url)
        )   
        user = request.POST['email']
        passw = request.POST['password']
        db = request.POST['db']
        uid = common.authenticate(db, user, passw, {})
        models = xmlrpc.client.ServerProxy(
        '{}/xmlrpc/2/object'.format(url)
        )
        hasRightApart = models.execute_kw(db, uid, passw, 'apartment.sell', 'check_access_rights', 
        ['read'], {'raise_exception': False})
        hasRightProduct = models.execute_kw(db, uid, passw, 'product.template', 'check_access_rights', 
        ['read'], {'raise_exception': False})
        if uid:
            if(hasRightApart & hasRightProduct):
                allApartment = get_apartment()
                return render(request,'apartment/apartment.html', {'apartments': allApartment})
        else:
                return HttpResponseRedirect("/")
    else:
        return HttpResponseRedirect("/loginAuth")

def create(name):
    models.execute_kw(db,uid,passw, 'res.partner', 'create', [{'name' : name}])

def get_offer_by_name(name):
    return models.execute_kw(db,uid,passw,'res.partner','search_read', [[('name', '=', name)]])

realtor_client/home/models.py
from django.db import models

class OdooUser(models.Model):  
    url = models.CharField(max_length=256)
    db = models.CharField(max_length=256)
    email = models.EmailField(max_length=256)
    password = models.CharField(max_length=256)

realtor_client/home/forms.py
from django import forms
from .models import OdooUser

class OdooUserForm(forms.Form):
    url = forms.CharField(label="URL", max_length=255)
    db = forms.CharField(label="db", max_length=255)
    email = forms.CharField(label="Email", max_length=255)
    password = forms.CharField(label="Password", max_length=255, widget = forms.PasswordInput())
    class Meta:
        model = OdooUser
        fields = ('url', 'db','email', 'password')

realtor_client/home/views.py
from django.views.generic import TemplateView
from .models import OdooUser
from .forms import OdooUserForm
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "home/index.html"
    model = OdooUser
    context_object_name = 'odooUsers'
    def get_context_data(self, **kwargs):
        context = super(HomeView,self).get_context_data(**kwargs)
        context['form'] = OdooUserForm
        return context

class LoginView(TemplateView):
    template_name = "home/login.html"
    model = OdooUser
    context_object_name = 'odooUsers'
    def get_context_data(self, **kwargs):
        context = super(LoginView,self).get_context_data(**kwargs)
        context['form'] = OdooUserForm
        return context

realtor_client/apartment/templates/apartment/apartment.html
{% extends "_base.html" %}

{% block content %}
    <h1>Bienvenue sur Realtor-Client</h1>
    <div class="d-flex p-2">
    {% for apart in apartments %}
        <div class="card bg-primary m-2 p-1 rounded-lg" style="width:300px">
            <div class="card-header">
                <img class="img-thumbnail" src="data:image/jpg;base64,{{apart.image}}"> <br> Name : {{ apart.name }}
            </div>
            <div class="card-body">
                availability : {{ apart.availability }}<br> description : {{ apart.description }} <br>
                price : {{ apart.price }}<br> apartment surface : {{ apart.apartment_surface }}<br> terrace surface : {{ apart.terrace_surface }} 
                <br> total surface : {{ apart.total_surface }} <br>best offerer : {{ apart.best_offerer }} <br>best price offer : {{ apart.best_price_offer }}
                <br> Quantity : {{ apart.qty_available }} 
            </div>
            <div class="input-group mb-3">
                <form action={% url 'apartment:offer' %} method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col">
                          <input name="offerer" type="text" class="form-control" placeholder="offerer" required>
                        </div>
                        <div class="col-5">
                          <input name="amount" type="number" class="form-control" placeholder="amount" required>
                        </div>
                        <div class="col">
                            <input type="hidden" name="connected" value="True">
                            <input type="hidden" name="apartment" value={{ apart.id }}>
                            <input type="hidden" name="best_offer" value={{ apart.best_price_offer }}>
                            <button class="btn btn-secondary" type="submit">offer</button>
                        </div>
                      </div>
                </form>
            </div>
        </div>
    {% endfor %}
    </div>
    <div >
        <h3 class="text-danger">{{error}}</h3>
    </div>
{% endblock content%}

realtor_client/home/templates/home/apartment.html
{% extends "_base.html" %}

{% block content %}
    <h1>Bienvenue sur Realtor-Client</h1>
    <div class="d-flex p-2">
    {% for apart in apartments %}
        <div class="card bg-primary m-2 p-1 rounded-lg" style="width:300px">
            <div class="card-header">
                Name : {{ apart.name }}
            </div>
            <div class="card-body">
                availability : {{ apart.availability }}<br> description : {{ apart.description }} <br>
                price : {{ apart.price }}<br> apartment surface : {{ apart.apartment_surface }}<br> terrace surface : {{ apart.terrace_surface }} 
                <br> total surface : {{ apart.total_surface }} <br>best offerer : {{ apart.best_offerer }} <br>best price offer : {{ apart.best_price_offer }}
                <br> Quantity : {{ apart.qty_available }}
            </div>
            <div class="input-group mb-3">
                <form action={% url 'home:offer' %} method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col">
                          <input name="offerer" type="text" class="form-control" placeholder="offerer" required>
                        </div>
                        <div class="col-5">
                          <input name="amount" type="number" class="form-control" placeholder="amount" required>
                        </div>
                        <div class="col">
                            <input type="hidden" name="connected" value="True">
                            <input type="hidden" name="apartment" value={{ apart.id }}>
                            <input type="hidden" name="best_offer" value={{ apart.best_price_offer }}>
                            <button class="btn btn-secondary" type="submit">offer</button>
                        </div>
                      </div>
                </form>
            </div>
        </div>
    {% endfor %}
    </div>
    <div >
        <h3 class="text-danger">{{error}}</h3>
    </div>
{% endblock content%}

realtor_client/home/templates/home/index.html
{% extends "_base.html" %}

{% block content %}
    <h1>Bienvenue sur Realtor-Client</h1>
    <a class="btn btn-primary" href={% url 'home:login' %}>Log in</a>
{% endblock content%}

realtor_client/home/templates/home/login.html
{% extends "_base.html" %}

{% load crispy_forms_tags %}
{% block title %}GProject - login{% endblock title %}

{% block content %}
<div class="container-sm p-3 mt-2 bg-light text-primary">
<h2>Log in</h2>
<form action="{% url 'apartment:apartment' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="hidden" name="connected" value="False"/>
    <button type="submit" class="btn btn-dark">Log in</button>
</form>
</div>
{% endblock content %}

realtor_client/templates/_base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block title %}MProject{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap
.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.
js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/po
pper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.m
in.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <div class="p-3 bg-primary">
        <h1 class="display-1">Realtor-Client</h1>
        <h2>Un site web d'achat d'appartement</h2>
    </div>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark bordertop border-white">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
              </li>
        </ul>
    </nav>
    {% block content %}
    {% endblock content %}
</body>

</html>

realtor_client/templates/_create_client_modal.html
<!-- Ajout d'un bouton pour faire apparaître la boîte de
dialogue -->
{% load crispy_forms_tags %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-dev-modal">Sign in</button>
<!-- Ajout du modal contenant le formulaire -->
<div class="modal fade " id="add-dev-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Sign in</h4>
                <button type="button" class="close" datadismiss="modal"><i class="fa fa-close"></i></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'home:create' %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div>
                        <button class="btn btn-primary" type="submit">Créer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>